import pandas as pd
import numpy as np

def calculate_trends_and_volatility(monthly_df):
    """
    Calculates behavioral features based on spending trends and volatility.
    Expects the pivot table generated by create_monthly_spending_table.
    """
    # Create a copy to avoid modifying the original dataframe
    df = monthly_df.copy()

    # 1. Calculate Total Monthly Expense
    # Since your pivot table already filtered for Expenses, 
    # we just sum all columns except 'month'
    expense_cols = [col for col in df.columns if col != 'month']
    df['total_expense'] = df[expense_cols].sum(axis=1)

    # 2. Rolling 3-Month Average
    # Smooths out anomalies to find the baseline spending habit
    df['rolling_3m_expense'] = df['total_expense'].rolling(window=3).mean()

    # 3. Spending Trend Slope
    # Percentage change month-over-month
    df['expense_mom_change'] = df['total_expense'].pct_change()

    # 4. Volatility: Coefficient of Variation (CV)
    # High CV = erratic/unpredictable spending behavior
    window = 3
    rolling_std = df['total_expense'].rolling(window=window).std()
    rolling_mean = df['total_expense'].rolling(window=window).mean()
    
    # Handle division by zero if mean is 0
    df['spending_volatility'] = rolling_std / rolling_mean

    return df